WebApi/Models/Promotion.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;

namespace WebApi.Models
{
    /// <summary>
    /// Акция
    /// </summary>
    [DataContract]
    public class Promotion
    {
        /// <summary>
        /// Идентификатор акции
        /// </summary>
        [DataMember(Name = "id")]
        [Required]
        public int Id { get; set; }

        /// <summary>
        /// Заголовок
        /// </summary>
        [DataMember(Name = "header")]
        [Display(Name = "Заголовок")]
        [Required]
        public string Header { get; set; }

        /// <summary>
        /// Описание
        /// </summary>
        [DataMember(Name = "description")]
        [Display(Name = "Описание")]
        [Required]
        public string Description { get; set; }

        /// <summary>
        /// Ссылка на картинку
        /// </summary>
        [DataMember(Name = "imageName")]
        [Required]
        public string ImageName { get; set; }

        /// <summary>
        /// Дата начала действия акции
        /// </summary>
        [Display(Name = "Дата начала действия акции")]
        public DateTime DtFrom { get; set; }

        /// <summary>
        /// Дата окончания действия акции
        /// </summary>
        [Display(Name = "Дата окончания действия акции")]
        public DateTime? DtTo { get; set; }
    }
}

WebApi/Controllers/PromotionsController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApi.Models;
using WebApi.Services;

namespace WebApi.Controllers
{

    /// <summary>
    /// Контроллер для работы с акциями
    /// </summary>
    [Route("[controller]")]
    public class PromotionsController : Controller
    {
        private readonly IPromotionService promotions;

        public PromotionsController(IPromotionService promotions)
        {
            this.promotions = promotions;
        }

        // GET api/promotions
        /// <summary>
        /// Получает списо акций
        /// </summary>
        [HttpGet]
        [Route("")]
        [Route("Index")]
        public async Task<IActionResult> IndexAsync()
        {
            return View("index",await this.promotions.GetActivePromotionsAsync());
        }

        // GET api/promotions/5
        /// <summary>
        /// Получает списо акций
        /// </summary>
        [HttpGet("{id:int}")]
        public async Task<IActionResult> DetailsAsync(int id)
        {
            return View(await this.promotions.GetPromotionAsync(id));
        }

        /// <summary>
        /// Получает списо акций
        /// </summary>
        [HttpGet("Edit/{id:int}")]
        public async Task<IActionResult> EditAsync(int id)
        {
            return View(await this.promotions.GetPromotionAsync(id));
        }

        /// <summary>
        /// Редактирует акцию
        /// </summary>
        [HttpPost("Edit")]
        public async Task<IActionResult> EditAsync([FromBody] PromotionUpsert promotion)
        {
            if (ModelState.IsValid)
            {
                var promotionId = await this.promotions.CreatePromotionAsync(promotion);
                return RedirectToAction($"DetailsAsync", new { id = promotionId });
            }                
            else
                return View(promotion);
        }


        /// <summary>
        /// Получает списо акций
        /// </summary>
        [HttpGet("Create")]
        public async Task<IActionResult> CreateAsync()
        {
            return View(new PromotionUpsert());
        }

        /// <summary>
        /// Создает акцию и открывает детализацию
        /// </summary>
        [HttpPost("Create")]
        public async Task<IActionResult> CreateAsync(PromotionUpsert promotion)
        {
            if (ModelState.IsValid)
            {
                var promotionId = await this.promotions.CreatePromotionAsync(promotion);
                return RedirectToAction($"DetailsAsync", new { id = promotionId });
            }                
            else
                return View(promotion);
        }

        /// <summary>
        /// Редактирует акцию
        /// </summary>
        [HttpPost("Delete")]
        public async Task<IActionResult> DeleteAsync(int Id)
        {
            await this.promotions.DeletePromotionAsync(Id);
            return RedirectToAction($"IndexAsync", null);
        }

    }
}

WebApi/Views/Promotions/CreateAsync.cshtml
@model WebApi.Models.PromotionUpsert
@{
    ViewData["Title"] = "Создание акции";
}

<h2>Создание акции</h2>

<form asp-action="Create" enctype="multipart/form-data" asp-controller="Promotions" asp-antiforgery="true">
    <div>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div>
            <label asp-for="Header"></label><br />
            <input asp-for="Header" />
            <span asp-validation-for="Header" />
        </div>
        <div>
            <label asp-for="Description"></label><br />
            <input asp-for="Description" />
            <span asp-validation-for="Description" />
        </div>
        <div>
            <label asp-for="DtFrom"></label><br />
            <input asp-for="DtFrom" />
            <span asp-validation-for="DtFrom" />
        </div>
        <div>
            <label asp-for="DtTo"></label><br />
            <input asp-for="DtTo" />
            <span asp-validation-for="DtTo" />
        </div>
        <div>
            <label asp-for="Image"></label><br />
            <input type="file" asp-for="Image" />
            <span asp-validation-for="Image" />
        </div>
        <div>
            <input class="btn btn-info" type="submit" value="Создать" />
        </div>
    </div>
</form>

WebApi/Views/Promotions/DetailsAsync.cshtml
@model WebApi.Models.PromotionDetails

@{
    ViewData["Title"] = "Описание акции";
    var dtStart = Model.DtFrom.ToString("dd.MM.yyyy");
    var dtEnd = Model.DtTo?.ToString("dd.MM.yyyy") ?? "не ограничено";
}


<div>
    <div class="card mb-3">
        <img class="card-img-top" src="data:image;base64,@System.Convert.ToBase64String(Model.Image)" alt="Card image cap">
        <div class="card-body">
            <h5 class="card-title"><h2>@Model.Header</h2></h5>
            <p class="card-text">@Model.Description</p>
            <p class="card-text"><small class="text-muted">Период действия с @dtStart по @dtEnd </small></p>
        </div>
    </div>
</div>

WebApi/Views/Promotions/EditAsync.cshtml
@model WebApi.Models.PromotionUpsert
@{
    ViewData["Title"] = "Создание акции";
}

<h2>Создание акции</h2>

<form asp-action="Create" enctype="multipart/form-data" asp-controller="Promotions" asp-antiforgery="true">
    <div>
        <div class="validation" asp-validation-summary="ModelOnly"></div>
        <div>
            <input asp-for="Id" />
        </div>
        <div>
            <label asp-for="Header"></label><br />
            <input asp-for="Header" />
            <span asp-validation-for="Header" />
        </div>
        <div>
            <label asp-for="Description"></label><br />
            <input asp-for="Description" />
            <span asp-validation-for="Description" />
        </div>
        <div>
            <label asp-for="DtFrom"></label><br />
            <input asp-for="DtFrom" />
            <span asp-validation-for="DtFrom" />
        </div>
        <div>
            <label asp-for="DtTo"></label><br />
            <input asp-for="DtTo" />
            <span asp-validation-for="DtTo" />
        </div>
        <div>
            <label asp-for="Image"></label><br />
            <input type="file" asp-for="Image" />
            <span asp-validation-for="Image" />
        </div>
        <div>
            <input class="btn btn-info" type="submit" value="Сохранить" />
        </div>
    </div>
</form>

WebApi/Views/Promotions/Index.cshtml
@model IEnumerable<WebApi.Models.Promotion>

@{
    ViewData["Title"] = "Список акций";
}
<h2>Список акций</h2>

<table class="table-condensed">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Id)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Header)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DtFrom)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DtTo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            var dtStart = item.DtFrom.ToString("dd.MM.yyyy");
            var dtEnd = item.DtTo?.ToString("dd.MM.yyyy") ?? "не ограничено";

            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Id)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Header)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @dtStart
                </td>
                <td>
                    @dtEnd
                </td>
                @*<td>
                        @Html.DisplayFor(modelItem => item.ImageName)
                    </td>*@
                <td>
                    <div>
                        @Html.ActionLink("Edit", "Edit", new { id = item.Id }, new { @class = "btn btn-warning" })
                        @Html.ActionLink("Details", "DetailsAsync", new { id = item.Id }, new { @class = "btn btn-success" })
                        @*@Html.ActionLink("Delete", "Delete", new { id = item.Id }, new { @class = "btn btn-danger", id = "#hl-delete-promotion" })*@
                        <form method="post" asp-controller="Promotions" asp-action="Delete" style="display: inline">
                            <input type="hidden" name="id" value=@item.Id />
                            <input class="btn btn-danger" type="submit" value="Delete" />
                        </form>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>
@Html.ActionLink("Create", "Create")